export const IPC_CHANNELS = {
  DEBUG_EVENT_LOG_CLEAR: "debug:event-log-clear",
  DEBUG_LOCAL_DATA_CLEAR: "debug:local-data-clear",
  DEBUG_EVENT_SEND: "debug:event-send",
  DEBUG_SNAPSHOT_GET: "debug:snapshot-get",
  DEBUG_SNAPSHOT_UPDATED: "debug:snapshot-updated",
  DECOR_GET: "decor:get",
  DECOR_UPDATED: "decor:updated",
  DECOR_UPDATE_SELECTION: "decor:update-selection",
  PROFILE_GET: "profile:get",
  PROFILE_UPDATED: "profile:updated",
  PROFILE_UPDATE_NAME: "profile:update-name",
  PROFILE_UPDATE_PERSONALITY: "profile:update-personality",
  PROFILE_UPDATE_SKIN: "profile:update-skin",
  PET_EVENT: "pet:event",
  STATS_SEVEN_DAYS_GET: "stats:seven-days:get",
  REPORT_GET: "report:get",
  SHARE_CARD_GENERATE: "share-card:generate",
  SHARE_CARD_REVEAL: "share-card:reveal"
} as const
